[project]
name = "lang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Varun Malewar", email = "vmmalewar@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "google-generativeai>=0.8.6",
    "huggingface-hub>=1.31.0",
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.2",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "numpy>=2.5.3",
    "openai>=3.13.0",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "transformers>=5.17.0",
]

[project.scripts]
lang = "lang:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
